#!/bin/bash

CRF=23
ENCODE=libx265
TUNE=psnr
PRESET=slow

if [[ ! $@ ]]; then
    echo 'mp4enc [option]... -i <input> [-o <output>]'
    echo
    echo 'OPTION'
    echo '    -a    The audio stream will be copy direct.'
    echo "    -e    The encode. A str like $ENCODE(default)."
    echo '    -f    The frame rate (Hz value).'
    echo "    -c    The video CRF value. A float like $CRF(default)."
    echo '    -n    The video noise reduce. Valid rage 0-10000.'
    echo "    -p    The video preset. A str like $PRESET(default)."
    echo '    -r    The video size. Syntax like "800x600".'
    echo '    -t    The video encoder tune. A str like $TUNE(default).'
	exit
else
    set -- $(getopt -qu -o "ae:n:i:p:t:q:o:r:f:" -n 'mp4enc' -- $@)
fi

which ffmpeg || exit

while [[ $@ ]]; do
    case $1 in
    -f)
        FPS=$2
        shift 2
	    ;;
    -a)
        NOAUDIO=1
        shift 1
        ;;
    -o)
        OUTPUT=$2
        shift 2
        ;;
    -c)
        CRF=$2
        shift 2
        ;;
    -e)
        ENCODE=$2
        shift 2
        ;;
    -i)
        INPUT=$2
        shift 2
        ;;
    -p)
        PRESET=$2
        shift 2
        ;;
    -n)
        NOISE=$2
        shift 2
        ;;
    -r)
        SIZE=$2
        shift 2
        ;;
    -t)
        TUNE=$2
        shift 2
        ;;
    --|*)
        shift 1
        ;;
    esac
done

if [ ! $INPUT ] || [ ! -f $INPUT ]; then
    echo 'You must specify a input file!'
    exit
fi

trap 'rm -f .$STAMP.*' EXIT

STAMP=$(date +%s)

ffmpeg -i $INPUT ${FPS:+-r $FPS} \
	-an ${SIZE:+-s $SIZE} ${NOISE:+-vf hqdn3d=$NOISE} \
	-c:v $ENCODE \
	-crf ${CRF:-23} ${TUNE:+-tune $TUNE} \
	-preset $PRESET .$STAMP.mp4 || exit

if [ $NOAUDIO ]; then
    ffmpeg -i $INPUT -vn -c:a copy .$STAMP.m4a
else
    ffmpeg -i $INPUT -vn -c:a aac -q:a 2 .$STAMP.m4a
fi

[ $OUTPUT ] || OUTPUT=${INPUT%\.*}.mp4

if [ -f $OUTPUT ]; then
    OUTPUT=${INPUT%\.*}_$((++_sx)).mp4
fi

if [ -f .$STAMP.m4a ]; then
    ffmpeg -i .$STAMP.mp4 -i .$STAMP.m4a -c copy -movflags +faststart $OUTPUT
else
    ffmpeg -i .$STAMP.mp4 -c copy -movflags +faststart $OUTPUT
fi
